<?php
/**
 * Options.
 *
 * @package GOAT PoL
 */

function pol_theme_add_acf_field_options()
{
	if( function_exists('acf_add_local_field_group') )
	{
	  acf_add_local_field_group(array(
	    'key' => 'group_6177d62e5f6bb',
	    'title' => 'Form Page',
	    'fields' => array(
	      array(
	        'key' => 'field_621382a62d80d',
	        'label' => 'Custom page title',
	        'name' => 'override_page_title',
	        'type' => 'text',
	        'instructions' => '',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'default_value' => '',
	        'placeholder' => '',
	        'prepend' => '',
	        'append' => '',
	        'maxlength' => '',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	      ),
	      array(
	        'key' => 'field_6177d62e624ff',
	        'label' => 'Form',
	        'name' => 'form_id',
	        'type' => 'post_object',
	        'instructions' => '',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'post_type' => array(
	          0 => 'af_form',
	        ),
	        'taxonomy' => '',
	        'allow_null' => 0,
	        'multiple' => 0,
	        'max' => '',
	        'return_format' => 'id',
	        'acfe_add_post' => 0,
	        'acfe_edit_post' => 0,
	        'save_custom' => 0,
	        'save_post_status' => 'publish',
	        'acfe_bidirectional' => array(
	          'acfe_bidirectional_enabled' => '0',
	        ),
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	        'ui' => 1,
	      ),
	      array(
	        'key' => 'field_6213822267074',
	        'label' => 'Introduction',
	        'name' => '',
	        'type' => 'acfe_post_field',
	        'instructions' => '',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'field_type' => 'content',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	      ),
	      array(
	        'key' => 'field_6177dbedc01c9',
	        'label' => 'Submit button',
	        'name' => 'form_submit_button',
	        'type' => 'text',
	        'instructions' => '',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'default_value' => '',
	        'placeholder' => '',
	        'prepend' => '',
	        'append' => '',
	        'maxlength' => '',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	      ),
	      array(
	        'key' => 'field_6177dcc091f96',
	        'label' => 'Submit action',
	        'name' => 'form_submit_action',
	        'type' => 'select',
	        'instructions' => '',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'choices' => array(
	          'message' => 'Display the success message',
	          'redirect' => 'Redirect to another page',
	          'post' => 'Redirect to the newly-created post',
	        ),
	        'default_value' => false,
	        'allow_null' => 0,
	        'multiple' => 0,
	        'max' => '',
	        'ui' => 0,
	        'return_format' => 'value',
	        'prepend' => '',
	        'append' => '',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	        'ajax' => 0,
	        'placeholder' => '',
	      ),
	      array(
	        'key' => 'field_6177db3795254',
	        'label' => 'Redirect page',
	        'name' => 'form_redirect_page',
	        'type' => 'page_link',
	        'instructions' => '',
	        'required' => 0,
	        'conditional_logic' => array(
	          array(
	            array(
	              'field' => 'field_6177dcc091f96',
	              'operator' => '==',
	              'value' => 'redirect',
	            ),
	          ),
	        ),
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'post_type' => array(
	          0 => 'page',
	        ),
	        'taxonomy' => '',
	        'allow_null' => 1,
	        'allow_archives' => 1,
	        'multiple' => 0,
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	      ),
	      array(
	        'key' => 'field_6214cea62d165',
	        'label' => 'Attach ID',
	        'name' => 'form_attach_id',
	        'type' => 'true_false',
	        'instructions' => '',
	        'required' => 0,
	        'conditional_logic' => array(
	          array(
	            array(
	              'field' => 'field_6177dcc091f96',
	              'operator' => '==',
	              'value' => 'redirect',
	            ),
	            array(
	              'field' => 'field_6177db3795254',
	              'operator' => '!=empty',
	            ),
	          ),
	        ),
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'message' => '',
	        'default_value' => 0,
	        'ui' => 1,
	        'ui_on_text' => '',
	        'ui_off_text' => '',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	      ),
	    ),
	    'location' => array(
	      array(
	        array(
	          'param' => 'page_template',
	          'operator' => '==',
	          'value' => 'page-templates/template-form.php',
	        ),
	      ),
	      array(
	        array(
	          'param' => 'page_template',
	          'operator' => '==',
	          'value' => 'page-templates/template-storyfinish.php',
	        ),
	      ),
	      array(
	        array(
	          'param' => 'page_template',
	          'operator' => '==',
	          'value' => 'page-templates/template-updatestory.php',
	        ),
	      ),
	      array(
	        array(
	          'param' => 'page_template',
	          'operator' => '==',
	          'value' => 'page-templates/template-finish.php',
	        ),
	      ),
	      array(
	        array(
	          'param' => 'page_template',
	          'operator' => '==',
	          'value' => 'page-templates/template-complete.php',
	        ),
	      ),
	    ),
	    'menu_order' => 0,
	    'position' => 'normal',
	    'style' => 'default',
	    'label_placement' => 'left',
	    'instruction_placement' => 'label',
	    'hide_on_screen' => array(
	      0 => 'author',
	      1 => 'block_editor',
	      2 => 'comments',
	      3 => 'discussion',
	      4 => 'excerpt',
	      5 => 'revisions',
	      6 => 'slug',
	    ),
	    'active' => true,
	    'description' => 'Configure pages on which forms are set to appear.',
	    'show_in_rest' => 0,
	    'acfe_autosync' => '',
	    'acfe_form' => 1,
	    'acfe_display_title' => 'Form Options',
	    'acfe_permissions' => '',
	    'acfe_meta' => '',
	    'acfe_note' => '',
	  ));
	  
	  acf_add_local_field_group(array(
	    'key' => 'group_621625a39c732',
	    'title' => 'Menu Item',
	    'fields' => array(
	      array(
	        'key' => 'field_621625a918812',
	        'label' => 'Mobile Icon',
	        'name' => 'mobile_icon',
	        'type' => 'text',
	        'instructions' => '',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_admin' => 0,
	        'default_value' => '',
	        'placeholder' => '',
	        'prepend' => '',
	        'append' => '',
	        'maxlength' => '',
	      ),
	    ),
	    'location' => array(
	      array(
	        array(
	          'param' => 'nav_menu_item',
	          'operator' => '==',
	          'value' => 'location/main',
	        ),
	      ),
	    ),
	    'menu_order' => 0,
	    'position' => 'normal',
	    'style' => 'default',
	    'label_placement' => 'left',
	    'instruction_placement' => 'label',
	    'hide_on_screen' => '',
	    'active' => true,
	    'description' => '',
	    'show_in_rest' => 0,
	    'acfe_autosync' => '',
	    'acfe_form' => 0,
	    'acfe_display_title' => '',
	    'acfe_meta' => '',
	    'acfe_note' => '',
	  ));
	  
	  acf_add_local_field_group(array(
	    'key' => 'group_623490eaee794',
	    'title' => 'Options: Images',
	    'fields' => array(
	      array(
	        'key' => 'field_623490eaf058c',
	        'label' => 'Goat Images',
	        'name' => 'goat_images',
	        'type' => 'gallery',
	        'instructions' => '',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_admin' => 0,
	        'return_format' => 'array',
	        'preview_size' => 'medium',
	        'insert' => 'append',
	        'library' => 'all',
	        'min' => '',
	        'max' => '',
	        'min_width' => '',
	        'min_height' => '',
	        'min_size' => '',
	        'max_width' => '',
	        'max_height' => '',
	        'max_size' => '',
	        'mime_types' => '',
	      ),
	    ),
	    'location' => array(
	      array(
	        array(
	          'param' => 'options_page',
	          'operator' => '==',
	          'value' => 'image-options',
	        ),
	      ),
	    ),
	    'menu_order' => 0,
	    'position' => 'normal',
	    'style' => 'default',
	    'label_placement' => 'left',
	    'instruction_placement' => 'label',
	    'hide_on_screen' => '',
	    'active' => true,
	    'description' => '',
	    'show_in_rest' => 0,
	    'acfe_autosync' => '',
	    'acfe_form' => 0,
	    'acfe_display_title' => 'Image Options',
	    'acfe_meta' => '',
	    'acfe_note' => '',
	  ));
	  
	  acf_add_local_field_group(array(
	    'key' => 'group_62348f953680d',
	    'title' => 'Options: Map',
	    'fields' => array(
	      array(
	        'key' => 'field_show_large_story_popup',
	        'label' => __('Open Large Story Popup', 'pol'),
	        'name' => 'show_large_story_popup',
	        'instructions' => __('When pressing "Read More...", open a larger popup over the map rather than redirect.', 'pol'),
	        'type' => 'true_false',
	        'ui' => 1,
					'ui_on_text' => __('Yes', 'pol'),
					'ui_off_text' => __('No', 'pol'),
	        'default_value' => 1,
	      ),
	      array(
	        'key' => 'field_show_stories_on_search',
	        'label' => __('Show Stories on Search', 'pol'),
	        'name' => 'show_stories_on_search',
	        'instructions' => __('While performing a search, show all stories popups matching the search.', 'pol'),
	        'type' => 'true_false',
	        'ui' => 1,
					'ui_on_text' => __('Yes', 'pol'),
					'ui_off_text' => __('No', 'pol'),
	        'default_value' => 0,
	      ),
	      array(
	        'key' => 'field_62348f9538776',
	        'label' => 'Google Maps API Key',
	        'name' => 'google_maps_api_key',
	        'type' => 'text',
	        'instructions' => 'Please ensure the <strong>Geocoding API</strong>, <strong>Maps JavaScript API</strong> and <strong>Places API</strong> are enabled. Read more <a href="https://developers.google.com/maps/documentation/javascript/get-api-key" target="_blank">here</a>.',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_admin' => 0,
	        'default_value' => '',
	        'maxlength' => '',
	        'placeholder' => '',
	        'prepend' => '',
	        'append' => '',
	      ),
	      array(
	        'key' => 'field_62348f953877b',
	        'label' => 'Map Style',
	        'name' => 'google_map_style',
	        'type' => 'select',
	        'instructions' => 'Sets the main homepage map style.',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_admin' => 0,
	        'choices' => array(
	          'roadmap' => 'Vector',
	          'hybrid' => 'Hybrid',
	          'satellite' => 'Satellite',
	        ),
	        'default_value' => 'roadmap',
	        'allow_null' => 0,
	        'multiple' => 0,
	        'max' => '',
	        'ui' => 0,
	        'return_format' => 'value',
	        'prepend' => '',
	        'append' => '',
	        'ajax' => 0,
	        'placeholder' => '',
	      ),
	      array(
	        'key' => 'field_62348f953877f',
	        'label' => 'Google Map ID',
	        'name' => 'google_map_id',
	        'type' => 'text',
	        'instructions' => 'An identifier required for customizing vector map styles (not needed for Hybrid or Satellite maps). Read more <a href="https://developers.google.com/maps/documentation/get-map-id" target="_blank">here</a>.',
	        'required' => 0,
	        'conditional_logic' => array(
	          array(
	            array(
	              'field' => 'field_62348f953877b',
	              'operator' => '==',
	              'value' => 'roadmap',
	            ),
	          ),
	        ),
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_admin' => 0,
	        'default_value' => '',
	        'placeholder' => '',
	        'prepend' => '',
	        'append' => '',
	        'maxlength' => '',
	      ),
	      array(
	        'key' => 'field_6234923c9cd99',
	        'label' => 'Initial Position',
	        'name' => 'google_map_initial_position',
	        'type' => 'google_map',
	        'instructions' => 'Set the initial centre position and zoom level on the homepage map.',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'acfe_google_map_preview' => '',
	        'center_lat' => '52.8814742',
	        'center_lng' => '6.84929598',
	        'height' => 400,
	        'acfe_google_map_zooms' => array(
	          'zoom' => '3',
	          'min_zoom' => '3',
	          'max_zoom' => '21',
	        ),
	        'acfe_google_map_marker_icon' => '',
	        'acfe_google_map_marker_width' => 50,
	        'acfe_google_map_type' => 'roadmap',
	        'acfe_google_map_disable_ui' => 0,
	        'acfe_google_map_disable_zoom_control' => 0,
	        'acfe_google_map_disable_map_type' => 1,
	        'acfe_google_map_disable_fullscreen' => 1,
	        'acfe_google_map_disable_streetview' => 1,
	        'acfe_google_map_style' => '[
	      {
	          "featureType": "administrative",
	          "elementType": "all",
	          "stylers": [
	              {
	                  "visibility": "on"
	              },
	              {
	                  "lightness": 33
	              }
	          ]
	      },
	      {
	          "featureType": "landscape",
	          "elementType": "all",
	          "stylers": [
	              {
	                  "color": "#efefef"
	              }
	          ]
	      },
	      {
	          "featureType": "landscape.man_made",
	          "elementType": "labels.text",
	          "stylers": [
	              {
	                  "visibility": "off"
	              }
	          ]
	      },
	      {
	          "featureType": "poi",
	          "elementType": "labels.text",
	          "stylers": [
	              {
	                  "visibility": "on"
	              }
	          ]
	      },
	      {
	          "featureType": "poi.attraction",
	          "elementType": "labels.text",
	          "stylers": [
	              {
	                  "visibility": "on"
	              }
	          ]
	      },
	      {
	          "featureType": "poi.business",
	          "elementType": "labels.text",
	          "stylers": [
	              {
	                  "visibility": "on"
	              }
	          ]
	      },
	      {
	          "featureType": "poi.business",
	          "elementType": "labels.icon",
	          "stylers": [
	              {
	                  "visibility": "off"
	              }
	          ]
	      },
	      {
	          "featureType": "poi.park",
	          "elementType": "geometry",
	          "stylers": [
	              {
	                  "color": "#e3eed3"
	              }
	          ]
	      },
	      {
	          "featureType": "poi.park",
	          "elementType": "labels",
	          "stylers": [
	              {
	                  "visibility": "on"
	              },
	              {
	                  "lightness": 20
	              }
	          ]
	      },
	      {
	          "featureType": "poi.place_of_worship",
	          "elementType": "labels.text",
	          "stylers": [
	              {
	                  "visibility": "off"
	              }
	          ]
	      },
	      {
	          "featureType": "poi.sports_complex",
	          "elementType": "labels.text",
	          "stylers": [
	              {
	                  "visibility": "off"
	              }
	          ]
	      },
	      {
	          "featureType": "road",
	          "elementType": "all",
	          "stylers": [
	              {
	                  "lightness": 20
	              }
	          ]
	      },
	      {
	          "featureType": "road.highway",
	          "elementType": "geometry",
	          "stylers": [
	              {
	                  "color": "#83a5b0"
	              }
	          ]
	      },
	      {
	          "featureType": "road.arterial",
	          "elementType": "geometry",
	          "stylers": [
	              {
	                  "color": "#bdcdd3"
	              }
	          ]
	      },
	      {
	          "featureType": "road.local",
	          "elementType": "geometry",
	          "stylers": [
	              {
	                  "color": "#ffffff"
	              }
	          ]
	      },
	      {
	          "featureType": "water",
	          "elementType": "all",
	          "stylers": [
	              {
	                  "visibility": "on"
	              },
	              {
	                  "color": "#b5cbe4"
	              }
	          ]
	      }
	  ]',
	        'acfe_google_map_key' => '',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	        'zoom' => '',
	        'zooms' => array(
	          'zoom' => 2,
	          'min_zoom' => 0,
	          'max_zoom' => 21,
	        ),
	      ),
	    ),
	    'location' => array(
	      array(
	        array(
	          'param' => 'options_page',
	          'operator' => '==',
	          'value' => 'map-options',
	        ),
	      ),
	    ),
	    'menu_order' => 0,
	    'position' => 'normal',
	    'style' => 'default',
	    'label_placement' => 'left',
	    'instruction_placement' => 'label',
	    'hide_on_screen' => '',
	    'active' => true,
	    'description' => '',
	    'show_in_rest' => 0,
	    'acfe_autosync' => '',
	    'acfe_form' => 1,
	    'acfe_display_title' => 'Map Options',
	    'acfe_permissions' => '',
	    'acfe_meta' => '',
	    'acfe_note' => '',
	  ));
	  
	  acf_add_local_field_group(array(
	    'key' => 'group_6165e5b858874',
	    'title' => 'Options: Messages',
	    'fields' => array(
	      array(
	        'key' => 'field_621d55324b65e',
	        'label' => 'Map Message',
	        'name' => 'map_message',
	        'type' => 'textarea',
	        'instructions' => 'The default message which appears on the homepage map when a visitor clicks "Send Us Your Writing".',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_admin' => 0,
	        'default_value' => '',
	        'placeholder' => '',
	        'maxlength' => '',
	        'rows' => 4,
	        'new_lines' => 'br',
	        'acfe_textarea_code' => 0,
	      ),
	      array(
	        'key' => 'field_62140aa929ba3',
	        'label' => '"Choose Location" Message',
	        'name' => 'choose_location_message',
	        'type' => 'textarea',
	        'instructions' => 'This message will be shown if a visitor lands on the "Add Story" page without having selected a location from the map or adding a new location.',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_admin' => 0,
	        'default_value' => '',
	        'placeholder' => '',
	        'maxlength' => '',
	        'rows' => 4,
	        'new_lines' => 'br',
	        'acfe_textarea_code' => 0,
	      ),
	      array(
	        'key' => 'field_621d46127fb90',
	        'label' => '"Wrong Location" Message',
	        'name' => 'wrong_location_message',
	        'type' => 'textarea',
	        'instructions' => 'This message will be shown if a visitor clicks on the "Wrong location" prompt on the "Add Story" page.',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_admin' => 0,
	        'default_value' => '',
	        'placeholder' => '',
	        'maxlength' => '',
	        'rows' => 4,
	        'new_lines' => 'br',
	        'acfe_textarea_code' => 0,
	      ),
	      array(
	        'key' => 'field_621d50ec8ed7c',
	        'label' => '"New Location" Message',
	        'name' => 'new_location_message',
	        'type' => 'textarea',
	        'instructions' => 'This message will be shown if a visitor clicks the "Send Us Your Writing" button when they are already on the new location page.',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_admin' => 0,
	        'default_value' => '',
	        'placeholder' => '',
	        'maxlength' => '',
	        'rows' => 4,
	        'new_lines' => 'br',
	        'acfe_textarea_code' => 0,
	      ),
	      array(
	        'key' => 'field_621d560480ba2',
	        'label' => 'Fallback Message',
	        'name' => 'fallback_message',
	        'type' => 'textarea',
	        'instructions' => 'The message shown on all other pages.',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_admin' => 0,
	        'default_value' => '',
	        'placeholder' => '',
	        'maxlength' => '',
	        'rows' => 4,
	        'new_lines' => 'br',
	        'acfe_textarea_code' => 0,
	      ),
	      array(
	        'key' => 'field_621d424f35d90',
	        'label' => '"Pending Story" Message',
	        'name' => 'pending_story_message',
	        'type' => 'textarea',
	        'instructions' => 'This message will be shown if a visitor submits a <strong>Long Story</strong> or a <strong>Long Story Short</strong> and must wait for it to be approved.',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_admin' => 0,
	        'default_value' => '',
	        'placeholder' => '',
	        'maxlength' => '',
	        'rows' => 4,
	        'new_lines' => 'br',
	        'acfe_textarea_code' => 0,
	      ),
	    ),
	    'location' => array(
	      array(
	        array(
	          'param' => 'options_page',
	          'operator' => '==',
	          'value' => 'messages',
	        ),
	      ),
	    ),
	    'menu_order' => 0,
	    'position' => 'normal',
	    'style' => 'default',
	    'label_placement' => 'left',
	    'instruction_placement' => 'label',
	    'hide_on_screen' => '',
	    'active' => true,
	    'description' => '',
	    'show_in_rest' => 0,
	    'acfe_autosync' => '',
	    'acfe_form' => 0,
	    'acfe_display_title' => 'Messages',
	    'acfe_meta' => '',
	    'acfe_note' => '',
	  ));
	  
	  acf_add_local_field_group(array(
	    'key' => 'group_6218d07bc7077019',
	    'title' => 'Story',
	    'fields' => array(
	      array(
	        'key' => 'field_623afede33e68',
	        'label' => 'Where does your story take place?',
	        'name' => 'where_does',
	        'type' => 'radio',
	        'instructions' => '',
	        'required' => '',
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'required_message' => '',
	        'hide_admin' => 0,
	        'choices' => array(
	          'geo_loc' => 'It\'s about a geographical location',
	          'about_books' => 'It\'s about a book',
	          'about_internet' => 'It\'s about the Internet',
	        ),
	        'allow_null' => 0,
	        'other_choice' => 0,
	        'default_value' => '',
	        'layout' => 'horizontal',
	        'return_format' => 'value',
	        'save_other_choice' => 0,
	      ),
	      array(
	        'key' => 'field_62566328a51c9',
	        'label' => 'What Is the Location ?',
	        'name' => 'place_location',
	        'type' => 'google_map',
	        'instructions' => 'If you choose a location by dropping a pin on the map, you may correct the name that appears in the box for "name of location.',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_admin' => 0,
	        'acfe_google_map_preview' => '',
	        'center_lat' => '6.510329986020568',
	        'center_lng' => '6.134632399999984',
	        'height' => '',
	        'acfe_google_map_zooms' => array(
	          'zoom' => '1',
	          'min_zoom' => '0',
	          'max_zoom' => '21',
	        ),
	        'acfe_google_map_marker_icon' => '',
	        'acfe_google_map_marker_width' => 50,
	        'acfe_google_map_type' => 'roadmap',
	        'acfe_google_map_disable_ui' => 0,
	        'acfe_google_map_disable_zoom_control' => 0,
	        'acfe_google_map_disable_map_type' => 0,
	        'acfe_google_map_disable_fullscreen' => 0,
	        'acfe_google_map_disable_streetview' => 0,
	        'acfe_google_map_style' => '',
	        'acfe_google_map_key' => '',
	        'zoom' => '',
	        'zooms' => array(
	          'zoom' => 2,
	          'min_zoom' => 0,
	          'max_zoom' => 21,
	        ),
	      ),
	      array(
	        'key' => 'field_6253489468389',
	        'label' => 'Location', //Story/Location Keywords
	        'name' => 'story_place_name',
	        'type' => 'text',
	        'instructions' => '',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'default_value' => '',
	        'placeholder' => '',
	        'prepend' => '',
	        'append' => '',
	        'maxlength' => '',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	      ),
	      array(
	        'key' => 'field_6218edc9e1b3d',
	        'label' => 'Give your story a title',
	        'name' => 'story_title',
	        'type' => 'text',
	        'instructions' => '',
	        'required' => 1,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'required_message' => 'You must give your story a title.',
	        'hide_admin' => 1,
	        'default_value' => '',
	        'placeholder' => '',
	        'prepend' => '',
	        'append' => '',
	        'maxlength' => '',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	      ),
	      array(
	        'key' => 'field_6218edece1b3e',
	        'label' => 'Story Type',
	        'name' => 'story_type',
	        'type' => 'taxonomy',
	        'instructions' => '',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'taxonomy' => 'story_type',
	        'field_type' => 'radio',
	        'max' => '',
	        'allow_null' => 0,
	        'add_term' => 0,
	        'save_terms' => 1,
	        'load_terms' => 1,
	        'return_format' => 'object',
	        'acfe_bidirectional' => array(
	          'acfe_bidirectional_enabled' => true,
	          'acfe_bidirectional_related' => array(
	            0 => 'field_6218d3d8944ab',
	          ),
	        ),
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	        'multiple' => 0,
	      ),
	      array(
	        'key' => 'field_6234b7dd4df00',
	        'label' => '<span><strong>Work with me first and publish later</strong><p>Your work will be given to our reader/advisor/editor (RAE) and they will tell about their thoughts. (NOTE: when you work with our RAE we’ll pay you to publish the final story.)</p></span>',
	        'name' => 'story_type_labels',
	        'type' => 'radio',
	        'instructions' => '',
	        'required' => 1,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => 'pol-hidden-acf',
	          'id' => '',
	        ),
	        'hide_field' => true,
	        'hide_label' => true,
	        'hide_instructions' => true,
	        'hide_required' => true,
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'required_message' => 'You must indicate a story type.',
	        'hide_admin' => 1,
	        'choices' => array(
	          
	          //quick take
	          'short-story' => !is_admin() ? '<span><strong>Ready to publish now</strong><p>My writing is ready to publish. Take a look and post it if you agree.</p></span>': '<span><strong>Ready to publish now</strong></span>',
	          'long-story-short' =>  !is_admin() ? '<span><strong>Work with RAE first and publish later</strong><p>Give my work to your reader/advisor/editor (RAE) and tell me what you think. (NOTE: when you work with our RAE we’ll pay you to publish the final story.)</strong></span>' : '<span><strong>Work with RAE first and publish later</strong></span>',
	        ),
	        'allow_null' => 0,
	        'other_choice' => 0,
	        'default_value' => '',
	        'layout' => 'vertical',
	        'return_format' => 'value',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	        'save_other_choice' => 0,
	      ),
	      array(
	        'key' => 'field_6234e129d916b',
	        'label' => 'Do you have a picture thats associated with your story?',
	        'name' => 'story_featured_image',
	        'type' => 'image',
	        'instructions' => 'Upload one here and it will appear with your story when it is published.',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 1,
	        'uploader' => 'basic',
	        'acfe_thumbnail' => 0,
	        'return_format' => 'id',
	        'preview_size' => 'medium',
	        'min_width' => '',
	        'min_height' => '',
	        'min_size' => '',
	        'max_width' => '',
	        'max_height' => '',
	        'max_size' => 128,
	        'mime_types' => '',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	        'library' => 'all',
	      ),
	      array(
	        'key' => 'field_6218ee25e1b3f',
	        'label' => 'What\'s your story?',
	        'name' => 'story',
	        'type' => 'wysiwyg',
	        'instructions' => '',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 1,
	        'default_value' => '',
	        'tabs' => 'visual',
	        'toolbar' => 'basic',
	        'media_upload' => 0,
	        'delay' => 0,
	        'acfe_wysiwyg_height' => 500,
	        'acfe_wysiwyg_max_height' => '',
	        'acfe_wysiwyg_valid_elements' => '',
	        'acfe_wysiwyg_custom_style' => '',
	        'acfe_wysiwyg_disable_wp_style' => 0,
	        'acfe_wysiwyg_autoresize' => 0,
	        'acfe_wysiwyg_disable_resize' => 0,
	        'acfe_wysiwyg_remove_path' => 0,
	        'acfe_wysiwyg_menubar' => 0,
	        'acfe_wysiwyg_transparent' => 0,
	        'acfe_wysiwyg_merge_toolbar' => 0,
	        'acfe_wysiwyg_custom_toolbar' => 0,
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	      ),
	      array(
	        'key' => 'field_621e14770fefa',
	        'label' => 'Writers Name',
	        'name' => 'story_nom_de_plume',
	        'type' => 'text',
	        'instructions' => '',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'default_value' => '',
	        'placeholder' => '',
	        'prepend' => '',
	        'append' => '',
	        'maxlength' => '',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	      ),
	      array(
	        'key' => 'field_621e149d0fefb',
	        'label' => 'Email Address',
	        'name' => 'story_email_address',
	        'type' => 'email',
	        'instructions' => '',
	        'required' => 1,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'required_message' => 'You must provide an email address.',
	        'hide_admin' => 0,
	        'default_value' => '',
	        'placeholder' => '',
	        'prepend' => '',
	        'append' => '',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	      ),
	      // array(
	      //   'key' => 'field_6234e07760da0',
	      //   'label' => 'Story',
	      //   'name' => '',
	      //   'type' => 'acfe_post_field',
	      //   'instructions' => '',
	      //   'required' => 0,
	      //   'conditional_logic' => 0,
	      //   'wrapper' => array(
	      //     'width' => '',
	      //     'class' => '',
	      //     'id' => '',
	      //   ),
	      //   'hide_field' => '',
	      //   'hide_label' => '',
	      //   'hide_instructions' => '',
	      //   'hide_required' => '',
	      //   'instruction_placement' => '',
	      //   'acfe_permissions' => '',
	      //   'hide_admin' => 0,
	      //   'field_type' => 'content',
	      //   'acfe_settings' => '',
	      //   'acfe_validate' => '',
	      // ),
	      array(
	        'key' => 'field_621e1528b7d7e',
	        'label' => 'Featured Story',
	        'name' => 'story_featured',
	        'type' => 'true_false',
	        'instructions' => '',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => '',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'message' => '',
	        'default_value' => 0,
	        'ui' => 1,
	        'ui_on_text' => '',
	        'ui_off_text' => '',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	      ),
	      array(
	        'key' => 'field_62360176aa6eb',
	        'label' => 'Accept Terms & Conditions',
	        'name' => 'story_accept_terms',
	        'type' => 'true_false',
	        'instructions' => '',
	        'required' => 1,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => 'no-label',
	          'id' => '',
	        ),
	        'hide_field' => '',
	        'hide_label' => 'all',
	        'hide_instructions' => '',
	        'hide_required' => '',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'required_message' => 'You must accept the terms and conditions.',
	        'hide_admin' => 1,
	        'message' => 'I have read and agree to the <a href="/our-agreement" target="_blank">terms and conditions</a>.',
	        'default_value' => 0,
	        'ui' => 0,
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	        'ui_on_text' => '',
	        'ui_off_text' => '',
	      ),
	      array(
	        'key' => 'field_621bd3d89a050',
	        'label' => 'What type of place is it?',
	        'name' => 'place_type',
	        'type' => 'checkbox',
	        'instructions' => 'Select all that apply.',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => 'pol-hidden-acf',
	          'id' => '',
	        ),
	        'hide_field' => true,
	        'hide_label' => true,
	        'hide_instructions' => true,
	        'hide_required' => 'admin',
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'choices' => array(
	          'cafe' => 'Café',
	          'library' => 'Library',
	          'hostel' => 'Hostel',
	          'park' => 'Public Park',
	          'store' => 'Store',
	          'community-center' => 'Community Center',
	          'archive' => 'Archive',
	          'legal-help' => 'Legal Help',
	          'transit' => 'Transit',
	          'doctor' => 'Doctor',
	        ),
	        'allow_custom' => 1,
	        'save_custom' => 1,
	        'default_value' => array(
	        ),
	        'layout' => 'vertical',
	        'toggle' => 0,
	        'return_format' => 'value',
	        'min' => '',
	        'max' => '',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	        'save_custom' => 0,
	      ),
	      array(
	        'key' => 'field_621bd4717aeff',
	        'label' => 'Is this place open and welcoming?',
	        'name' => 'place_access',
	        'type' => 'checkbox',
	        'instructions' => 'Select all that apply.',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => 'pol-hidden-acf',
	          'id' => '',
	        ),
	        'hide_field' => true,
	        'hide_label' => true,
	        'hide_instructions' => true,
	        'hide_required' => true,
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'choices' => array(
	          'gratis' => 'Gratis (no payment)',
	          'public' => 'Public (not private)',
	          'all-ages' => 'All ages (young and old are welcome)',
	          'anonymous' => 'Anonymous (no ID or registering required)',
	          'welcoming' => 'Welcoming (I feel welcome)',
	          'good-mix' => 'Good mix (lots of different people here)',
	          'friendly' => 'Friendly (no police or armed guards)',
	          'open-access' => 'Open access (come and go as you please)',
	          'none' => 'None of the above',
	        ),
	        'allow_custom' => 1,
	        'save_custom' => 1,
	        'default_value' => array(
	        ),
	        'layout' => 'vertical',
	        'toggle' => 0,
	        'return_format' => 'value',
	        'min' => '',
	        'max' => '',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	        'save_custom' => 0,
	      ),
	      array(
	        'key' => 'field_6218d70ee719e',
	        'label' => 'What languages are spoken here?',
	        'name' => 'place_languages',
	        'type' => 'select',
	        'instructions' => 'Select all that apply.',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => 'pol-hidden-acf',
	          'id' => 'finish-story-select',
	        ),
	        'hide_field' => true,
	        'hide_label' => true,
	        'hide_instructions' => true,
	        'hide_required' => true,
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'choices' => array(
	          'afrikaans' => 'Afrikaans',
	          'albanian' => 'Albanian',
	          'arabic' => 'Arabic',
	          'armenian' => 'Armenian',
	          'basque' => 'Basque',
	          'bengali' => 'Bengali',
	          'bulgarian' => 'Bulgarian',
	          'catalan' => 'Catalan',
	          'cambodian' => 'Cambodian',
	          'chinese' => 'Chinese (Mandarin)',
	          'croatian' => 'Croatian',
	          'czech' => 'Czech',
	          'danish' => 'Danish',
	          'dutch' => 'Dutch',
	          'english' => 'English',
	          'estonian' => 'Estonian',
	          'fiji' => 'Fiji',
	          'finnish' => 'Finnish',
	          'french' => 'French',
	          'georgian' => 'Georgian',
	          'german' => 'German',
	          'greek' => 'Greek',
	          'gujarati' => 'Gujarati',
	          'hebrew' => 'Hebrew',
	          'hindi' => 'Hindi',
	          'hungarian' => 'Hungarian',
	          'icelandic' => 'Icelandic',
	          'indonesian' => 'Indonesian',
	          'irish' => 'Irish',
	          'italian' => 'Italian',
	          'japanese' => 'Japanese',
	          'javanese' => 'Javanese',
	          'korean' => 'Korean',
	          'latin' => 'Latin',
	          'latvian' => 'Latvian',
	          'lithuanian' => 'Lithuanian',
	          'macedonian' => 'Macedonian',
	          'malay' => 'Malay',
	          'malayalam' => 'Malayalam',
	          'maltese' => 'Maltese',
	          'maori' => 'Maori',
	          'marathi' => 'Marathi',
	          'mongolian' => 'Mongolian',
	          'nepali' => 'Nepali',
	          'norwegian' => 'Norwegian',
	          'persian' => 'Persian',
	          'polish' => 'Polish',
	          'portuguese' => 'Portuguese',
	          'punjabi' => 'Punjabi',
	          'quechua' => 'Quechua',
	          'romanian' => 'Romanian',
	          'russian' => 'Russian',
	          'samoan' => 'Samoan',
	          'serbian' => 'Serbian',
	          'slovak' => 'Slovak',
	          'slovenian' => 'Slovenian',
	          'spanish' => 'Spanish',
	          'swahili' => 'Swahili',
	          'swedish' => 'Swedish',
	          'tamil' => 'Tamil',
	          'tatar' => 'Tatar',
	          'telugu' => 'Telugu',
	          'thai' => 'Thai',
	          'tibetan' => 'Tibetan',
	          'tonga' => 'Tonga',
	          'turkish' => 'Turkish',
	          'ukrainian' => 'Ukrainian',
	          'urdu' => 'Urdu',
	          'uzbek' => 'Uzbek',
	          'vietnamese' => 'Vietnamese',
	          'welsh' => 'Welsh',
	          'xhosa' => 'Xhosa',
	        ),
	        'allow_custom' => 1,
	        'default_value' => array(
	        ),
	        'allow_null' => 0,
	        'multiple' => 1,
	        'min' => '',
	        'max' => '',
	        'ui' => 1,
	        'ajax' => 0,
	        'return_format' => 'value',
	        'allow_custom' => 1,
	        'placeholder' => 'Search for a language',
	        'prepend' => '',
	        'append' => '',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	      ),
	      array(
	        'key' => 'field_621bd4bf6cba8',
	        'label' => 'What can people find here? What is it good for?',
	        'name' => 'place_attributes',
	        'type' => 'checkbox',
	        'instructions' => 'This place is helpful if... (Select all that apply)',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => 'pol-hidden-acf',
	          'id' => '',
	        ),
	        'hide_field' => true,
	        'hide_label' => true,
	        'hide_instructions' => true,
	        'hide_required' => true,
	        'instruction_placement' => '',
	        'acfe_permissions' => '',
	        'hide_admin' => 0,
	        'choices' => array(
	          'hungry' => 'You are hungry',
	          'tired' => 'You are tired',
	          'travel' => 'You need to travel',
	          'information' => 'You need information',
	          'lonely' => 'You are lonely',
	          'be-alone' => 'You want to be left alone',
	          'threatened' => 'You have been threatened',
	          'safety' => 'You need safety',
	          'work' => 'You need work',
	          'money' => 'You need money',
	          'reading' => 'You want to read',
	          'writing' => 'You want to write',
	          'read-or-heard' => 'You want to be read (or be heard)',
	          'learn-teach-skills' => 'You want to learn/teach skills',
	          'no-answer' => 'I don\'t want to answer',
	        ),
	        'allow_custom' => 1,
	        'save_custom' => 1,
	        'default_value' => array(
	        ),
	        'layout' => 'vertical',
	        'toggle' => 0,
	        'return_format' => 'value',
	        'min' => '',
	        'max' => '',
	        'acfe_settings' => '',
	        'acfe_validate' => '',
	        'save_custom' => 0,
	      ),
	      array(
	        'key' => 'field_625d2c3e4d9f8',
	        'label' => 'Check Form',
	        'name' => 'check_form',
	        'type' => 'acfe_hidden',
	        'instructions' => '',
	        'required' => 0,
	        'conditional_logic' => 0,
	        'wrapper' => array(
	          'width' => '',
	          'class' => '',
	          'id' => '',
	        ),
	        'hide_admin' => 1,
	        'default_value' => 'edit-form',
	      ),
	    ),
	    'location' => array(
	      array(
	        array(
	          'param' => 'af_form',
	          'operator' => '==',
	          'value' => 'form_6258fbdf1988b',
	        ),
	      ),
	      
	    ),
	    'menu_order' => 0,
	    'position' => 'normal',
	    'style' => 'default',
	    'label_placement' => 'left',
	    'instruction_placement' => 'label',
	    'hide_on_screen' => '',
	    'active' => true,
	    'description' => '',
	    'show_in_rest' => 0,
	    'acfe_autosync' => '',
	    'acfe_form' => 1,
	    'acfe_display_title' => '',
	    'acfe_permissions' => '',
	    'acfe_meta' => '',
	    'acfe_note' => '',
	  ));
	}
}

add_action('acf/init', 'pol_theme_add_acf_field_options');
